export {
  ROUTE_ADMIN_MASTER_BASE,
  ROUTE_ADMIN_MASTER_CITY,
  ROUTE_ADMIN_MASTER_STATE,
  ROUTE_ADMIN_MASTER_QUALIFICATION,
  ROUTE_ADMIN_MASTER_DEPARTMENT,
  ROUTE_ADMIN_MASTER_AVAILABILITY,
  ROUTE_ADMIN_MASTER_SHIFT_TIME,
} from "@app/router/routePaths";
