export {
  ROUTE_HOME,
  ROUTE_LOGIN,
  ROUTE_REGISTER,
  ROUTE_FORGOT_PASSWORD,
  ROUTE_CONTACT,
  ROUTE_BLOOD_DONATION,
  ROUTE_FREE_HEALTH_CHECKUPS,
  ROUTE_PATIENT_REGISTRATION,
  ROUTE_MS_ADMIN_BASE,
  ROUTE_MS_ADMIN_DASHBOARD,
  ROUTE_MS_ADMIN_UPDATE_PROFILE,
  ROUTE_MS_ADMIN_DUTY_CHART,
  ROUTE_MS_ADMIN_MASTER_SEARCH,
  ROUTE_MS_ADMIN_DAILY_REPORT,
  ROUTE_MS_ADMIN_REGISTRATION_REPORT,
  ROUTE_MS_ADMIN_MASTER_REPORT,
  ROUTE_ADMIN_BASE,
  ROUTE_ADMIN_DASHBOARD,
  ROUTE_ADMIN_USERS,
  ROUTE_ADMIN_REGISTRATION_REPORT,
  ROUTE_ADMIN_DAILY_REPORT,
  ROUTE_ADMIN_DUTY_CHART,
  ROUTE_ADMIN_MASTER_SEARCH,
  ROUTE_ADMIN_MASTER_REPORT,
  ROUTE_ADMIN_FREE_HEALTH_CHECKUP,
  ROUTE_ADMIN_BLOOD_DONATION,
  ROUTE_ADMIN_PROFILE,
  ROUTE_ADMIN_MASTER_BASE,
  ROUTE_ADMIN_MASTER_CITY,
  ROUTE_ADMIN_MASTER_STATE,
  ROUTE_ADMIN_MASTER_QUALIFICATION,
  ROUTE_ADMIN_MASTER_DEPARTMENT,
  ROUTE_ADMIN_MASTER_AVAILABILITY,
  ROUTE_ADMIN_MASTER_SHIFT_TIME,
  ROUTE_MS_BASE,
  ROUTE_MS_DASHBOARD,
  ROUTE_MS_UPDATE_PROFILE,
} from "./routePaths";

export { getDefaultRouteForUserType } from "./authRedirects";
export { legacyProtectedRouteEntries } from "./protectedRouteEntries";
export { adminRouteEntries } from "./adminRouteEntries";
export { createProtectedRoute, createProtectedRoutes } from "./createProtectedRoute";
export { createAdminRoutes, AdminRoutes } from "./createAdminRoutes";
export { LegacyRedirectRoutes } from "./legacyRedirectRoutes";
export { routeMeta, getRouteMeta, type RouteMeta, type UserRole } from "./routeMeta";
