import type { CampAdminRecord } from "./types";

const now = () => new Date().toISOString();

export const CAMP_SEED_DATA: CampAdminRecord[] = [
  {
    id: "fhc-mumbai-east",
    campType: "health-checkup",
    title: "Thane East Wellness Camp",
    shortDescription:
      "Services available: vital screening, doctor consult, referral support.",
    organizerName: "Sewa Health Collective",
    fullAddress: "Zilla Parishad Ground, Thane East, Mumbai, Maharashtra 400603",
    landmark: "Next to Doshi Hospital",
    driveDate: "Friday, June 28, 2026",
    startTime: "9:00 AM",
    endTime: "3:00 PM",
    phone: "+91 98200 12345",
    email: "thane.health@medicalsewa.org",
    entryType: "walk-in",
    status: "published",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "fhc-chennai-senior",
    campType: "health-checkup",
    title: "Nungambakkam Senior Care Clinic",
    shortDescription:
      "Services available: blood pressure check, medication review, health coaching.",
    organizerName: "Tamil Nadu Health Network",
    fullAddress: "Community Hall, Nungambakkam, Chennai, Tamil Nadu 600034",
    landmark: "Opposite Women's College",
    driveDate: "Monday, July 4, 2026",
    startTime: "10:00 AM",
    endTime: "4:00 PM",
    phone: "+91 98400 98765",
    email: "tnhealth@medicalsewa.org",
    entryType: "appointment",
    status: "published",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "fhc-pune-youth",
    campType: "health-checkup",
    title: "Pune Youth Wellness Drive",
    shortDescription:
      "Services available: vision screening, mental wellness, lifestyle coaching.",
    organizerName: "Medical Sewa Foundation",
    fullAddress: "MIT Sports Complex, Kothrud, Pune, Maharashtra 411038",
    landmark: "Near the main gate",
    driveDate: "Sunday, July 12, 2026",
    startTime: "8:30 AM",
    endTime: "2:30 PM",
    phone: "+91 020 2546 7890",
    email: "punewellness@medicalsewa.org",
    entryType: "walk-in",
    status: "published",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "fhc-mumbai-family",
    campType: "health-checkup",
    title: "Andheri West Family Health Check",
    shortDescription:
      "Services available: child health assessment, family screening, referral pathways.",
    organizerName: "Mumbai Wellness Alliance",
    fullAddress: "St. Andrews School Grounds, Andheri West, Mumbai, Maharashtra 400058",
    landmark: "Beside the chapel",
    driveDate: "Sunday, July 19, 2026",
    startTime: "9:30 AM",
    endTime: "5:00 PM",
    phone: "+91 96190 23456",
    email: "mumbai.wellness@medicalsewa.org",
    entryType: "appointment",
    status: "draft",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "camp-mumbai-may",
    campType: "blood-donation",
    title: "Blood donation camp Mumbai",
    shortDescription:
      "High-capacity donation drive with refreshments and counselling for first-time donors.",
    organizerName: "Medical Sewa & Mumbai Hospitals Consortium",
    fullAddress:
      "Community Hall, JVPD Scheme, Near SNDT University, Mumbai, Maharashtra 400049",
    landmark: "Near SNDT University",
    driveDate: "Tue, 12 May, 2026",
    startTime: "9:00 AM",
    endTime: "5:00 PM",
    phone: "+91 8898209852",
    email: "snmdispensary@gmail.com",
    entryType: "walk-in",
    status: "published",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "camp-chennai",
    campType: "blood-donation",
    title: "Apollo community drive Chennai",
    shortDescription:
      "Focus on Bombay blood group and Rh-negative donors. Shuttle support nearby.",
    organizerName: "Apollo Outreach & Medical Sewa",
    fullAddress:
      "Apollo Speciality Annex, Pondy Bazaar Approach, Chennai, Tamil Nadu 600017",
    landmark: "Near Pondy Bazaar Approach",
    driveDate: "Sun, 18 May, 2026",
    startTime: "8:30 AM",
    endTime: "3:30 PM",
    phone: "+91 8898209852",
    email: "snmdispensary@gmail.com",
    entryType: "appointment",
    status: "published",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "camp-pune",
    campType: "blood-donation",
    title: "Pune university township drive",
    shortDescription:
      "Collaboration with campuses and NGOs to widen youth participation safely.",
    organizerName: "Medical Sewa Volunteers — Pune Circle",
    fullAddress: "SVM Hall, Behind Karve Statue, Kothrud, Pune, Maharashtra 411038",
    landmark: "Behind Karve Statue",
    driveDate: "Sat, 24 May, 2026",
    startTime: "10:00 AM",
    endTime: "4:30 PM",
    phone: "+91 8898209852",
    email: "snmdispensary@gmail.com",
    entryType: "walk-in",
    status: "draft",
    createdAt: now(),
    updatedAt: now(),
  },
];
